title: Python and C++ Samples
description: Python and C++ Samples
google_analytics: 
footer-links:
  github: devchait
permalink: /docs/blog/:year/:month/:day/:title
github_comments_repository: devchait.github.io
fenced_code_blocks: true


