baseURL = "https://python-samples.github.io/"
title = "Python Samples"
theme = "hyde-hyde"

[params]
  author = "Chaitanya Khire"
  title = "AI/ML Engineer"
  # description = "..."
  authorimage = "/img/devchait.jpg"
  dateformat = "June 20, 2020"

  # sidebar, copyright & license
  copyright = "htr3n"
  since = 2019
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  showBuiltWith = true

  # https://highlightjs.org
  highlightjs = true
  highlightjsstyle = "github"
    
[params.social]
  github = "devchait"
  #instagram = ""
  linkedin = "devchait"
  stackoverflow = "8074788/chaitanya-khire"
  email = "devchait@gmail.com"

## Main Menu
[[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/post/design-patterns/builder-pattern"

[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"
